/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author alumnogreibd
 */
public class VLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VLogin.class.getName());
    private aplicacion.FachadaAplicacion fa;

    /**
     * Creates new form VLogin
     */
    public VLogin(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        botonAceptar = new javax.swing.JButton();
        textoCuenta = new javax.swing.JLabel();
        botonCrearCuenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoEmail.setText("Email:");

        jLabel2.setText("Contraseña");

        PasswordField.setToolTipText("");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(this::botonAceptarActionPerformed);

        textoCuenta.setText("¿No tienes cuenta?");

        botonCrearCuenta.setText("Crear Cuenta");
        botonCrearCuenta.addActionListener(this::botonCrearCuentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoEmail)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldEmail)
                            .addComponent(PasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(botonAceptar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textoCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(botonCrearCuenta)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(botonAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCuenta)
                    .addComponent(botonCrearCuenta))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String email = textFieldEmail.getText().trim();
        String clave = new String(PasswordField.getPassword());

        if (email.isEmpty() || clave.isEmpty()) {
            fa.muestraExcepcion("Por favor rellena todos los campos");
            return;
        }

        aplicacion.Usuario u = fa.autenticar(email, clave);

        if (u == null) {
            fa.muestraExcepcion("Email o contraseña incorrectos");
        } else if (u.isPermisos()) {
            dispose();
            fa.abrirPortalAdmin();
        } else {
            dispose();
            fa.abrirPortalUsuario(u);
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        new VCrearCuenta(fa).setVisible(true);
    }//GEN-LAST:event_botonCrearCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JLabel textoCuenta;
    private javax.swing.JLabel textoEmail;
    // End of variables declaration//GEN-END:variables
}
