/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import aplicacion.Usuario;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class VCompraEntradas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VCompraEntradas.class.getName());
    private FachadaAplicacion fa;
    private Usuario usuarioActual;


    VCompraEntradas(FachadaAplicacion fa, Usuario usuarioActual) {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelNombre = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        labelFechaVisita = new javax.swing.JLabel();
        textFechaVisita = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        labelCash = new javax.swing.JLabel();
        labelNEntradas = new javax.swing.JLabel();
        comboboxNentradas = new javax.swing.JComboBox<>();
        botonConfirmarCompra = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Compra de entradas");
        jScrollPane1.setViewportView(jTextArea1);

        labelNombre.setText("Nombre");

        labelFechaVisita.setText("Fecha de visita");

        labelPrecio.setText("Precio");

        labelCash.setText("$12 / entrada");

        labelNEntradas.setText("Número de entradas");

        comboboxNentradas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        botonConfirmarCompra.setText("Confirmar compra");
        botonConfirmarCompra.addActionListener(this::botonConfirmarCompraActionPerformed);

        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelFechaVisita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFechaVisita))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNombre))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNEntradas)
                            .addComponent(botonConfirmarCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboboxNentradas, 0, 125, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(labelPrecio)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCash, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelFechaVisita)
                    .addComponent(textFechaVisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCash))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNEntradas)
                    .addComponent(comboboxNentradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConfirmarCompra)
                    .addComponent(botonSalir))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonConfirmarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfirmarCompraActionPerformed
        try {
            String fechaStr = textFechaVisita.getText().trim();
            if (fechaStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Introduzca una fecha (YYYY-MM-DD)");
                return;
            }
        
            LocalDate fecha = LocalDate.parse(fechaStr);
            int numEntradas = Integer.parseInt((String) comboboxNentradas.getSelectedItem());
        
            // Comprobar disponibilidad
            if (!fa.verificarDisponibilidadEntradas(fecha, numEntradas)) {
                int disponibles = fa.verificarDisponibilidadEntradas(fecha, 999) ? 1000 : 
                                (1000 - fa.consultarEntradasVendidas(fecha, fecha).size());
                JOptionPane.showMessageDialog(this, 
                    "No hay suficientes entradas disponibles para ese día.\n" +
                    "Disponibles: " + disponibles);
                return;
            }
        
            double precioTotal = numEntradas * 25.50;
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Confirmar compra de " + numEntradas + " entrada(s) para el " + fecha + 
                "\nPrecio total: " + precioTotal + "€",
                "Confirmar compra", JOptionPane.YES_NO_OPTION);
        
            if (confirm == JOptionPane.YES_OPTION) {
                boolean ok = fa.comprarEntradas(fecha, numEntradas, usuarioActual.getIdUsuario());
                if (ok) {
                    JOptionPane.showMessageDialog(this, "Compra realizada con éxito");
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error en la compra");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_botonConfirmarCompraActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed


    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        ///java.awt.EventQueue.invokeLater(() -> new VCompraEntradas().setVisible(true));
    //}
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConfirmarCompra;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboboxNentradas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelCash;
    private javax.swing.JLabel labelFechaVisita;
    private javax.swing.JLabel labelNEntradas;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JTextField textFechaVisita;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
