/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author alumnogreibd
 */
public class VCrearCuenta extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VCrearCuenta.class.getName());

    /**
     * Creates new form VCrearCuenta
     */
    private aplicacion.FachadaAplicacion fa;

    public VCrearCuenta(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoNombre = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoTelefono = new javax.swing.JLabel();
        textoContraseña = new javax.swing.JLabel();
        textoFechaNacimiento = new javax.swing.JLabel();
        botonCrearCuenta = new javax.swing.JButton();
        textFieldNombre = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldFechaNacimiento = new javax.swing.JTextField();
        fieldContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoNombre.setText("Nombre:");
        textoNombre.setToolTipText("");

        textoEmail.setText("Email:");

        textoTelefono.setText("Teléfono:");

        textoContraseña.setText("Contraseña:");

        textoFechaNacimiento.setText("Fecha Nacimiento:");

        botonCrearCuenta.setText("Crear Cuenta");
        botonCrearCuenta.addActionListener(this::botonCrearCuentaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonCrearCuenta)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoEmail)
                                    .addComponent(textoNombre)
                                    .addComponent(textoFechaNacimiento))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoTelefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoContraseña, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldNombre)
                            .addComponent(textFieldEmail)
                            .addComponent(textFieldTelefono)
                            .addComponent(textFieldFechaNacimiento)
                            .addComponent(fieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNombre)
                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTelefono)
                    .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoContraseña)
                    .addComponent(fieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFechaNacimiento)
                    .addComponent(textFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonCrearCuenta)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearCuentaActionPerformed
        String nombre = textFieldNombre.getText().trim();
        String email  = textFieldEmail.getText().trim();
        String telefono = textFieldTelefono.getText().trim();
        String clave  = new String(fieldContraseña.getPassword());
        String fechaStr = textFieldFechaNacimiento.getText().trim();

        // Validar que no haya campos vacíos
        if (nombre.isEmpty() || email.isEmpty() || clave.isEmpty() || fechaStr.isEmpty()) {
            fa.muestraExcepcion("Por favor rellena todos los campos obligatorios");
            return;
        }

        // Convertir fecha
        java.time.LocalDate fechaNacimiento;
        try {
            fechaNacimiento = java.time.LocalDate.parse(fechaStr);
        } catch (Exception e) {
            fa.muestraExcepcion("Formato de fecha incorrecto. Usa YYYY-MM-DD");
        return;
        }

        // T3/T4 - Crear cuenta
        aplicacion.Usuario u = new aplicacion.Usuario(nombre, "", "", clave, email, telefono, fechaNacimiento);
        fa.crearCuenta(u);
    
        fa.muestraExcepcion("Cuenta creada correctamente");
        dispose();
    }//GEN-LAST:event_botonCrearCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearCuenta;
    private javax.swing.JPasswordField fieldContraseña;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldFechaNacimiento;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTelefono;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoFechaNacimiento;
    private javax.swing.JLabel textoNombre;
    private javax.swing.JLabel textoTelefono;
    // End of variables declaration//GEN-END:variables
}
