/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Espectaculo;
import aplicacion.FachadaAplicacion;
import java.security.Timestamp;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumnogreibd
 */
public class VGestionEspectaculos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VGestionEspectaculos.class.getName());

    private FachadaGui fgui; // Referencia a la fachada
    private final FachadaAplicacion fa;

    /**
     * Constructor modificado para integrarse en la aplicación
     */
    public VGestionEspectaculos(java.awt.Frame parent, boolean modal, FachadaGui fgui) {
        super(parent, modal);
        this.fgui = fgui;
        this.fa = fgui.getFachadaAplicacion();
        initComponents();
        this.setLocationRelativeTo(parent);
        cargarEspectaculos();
        cargarZonas();
        cargarShowmans();
    }
    
    private void cargarZonas() {
        List<String> zonas = fa.obtenerNombresZonas();
        jComboBox1.removeAllItems();
        for (String zona : zonas) {
            jComboBox1.addItem(zona);
        }
    }
    
    private void cargarEspectaculos() {
        List<Espectaculo> espectaculos = fa.listarEspectaculos();
    
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"ID", "Nombre", "Zona", "Inicio", "Duración", "Aforo", "Plazas", "Showman"}, 0);
    
        for (Espectaculo e : espectaculos) {
            modelo.addRow(new Object[]{
                e.getIdEspectaculo(),
                e.getNombre(),
                e.getZona(),
                e.getHoraInicio(),
                e.getDuracion(),
                e.getAforo(),
                e.getPlazasDisponibles(),
                e.getShowman()
            });
        }
        tablaEspectaculos.setModel(modelo);
    }
    
    private void cargarShowmans() {
    comboShowman.removeAllItems();
    comboShowman.addItem("");
    java.util.List<aplicacion.Trabajador> trabajadores = fa.listarTrabajadores();
    for (aplicacion.Trabajador t : trabajadores) {
        if ("Showman".equals(t.getTipoTrabajo())) {
            comboShowman.addItem(t.getDni());
            }
        }
    }
    
    private void limpiarFormulario() {
        textFieldID.setText("");
        textFieldNombre.setText("");
        textFieldInicio.setText("");
        textFieldDuracion.setText("");
        textFieldAforo.setText("");
        textFieldPlazas.setText("");
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        titular = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEspectaculos = new javax.swing.JTable();
        panelDetalles = new javax.swing.JPanel();
        textID = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        textNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textZona = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textInicio = new javax.swing.JLabel();
        textFieldInicio = new javax.swing.JTextField();
        textDuracion = new javax.swing.JLabel();
        textFieldDuracion = new javax.swing.JTextField();
        textAforo = new javax.swing.JLabel();
        textFieldAforo = new javax.swing.JTextField();
        textPlazas = new javax.swing.JLabel();
        textFieldPlazas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        comboShowman = new javax.swing.JComboBox<>();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titular.setColumns(20);
        titular.setRows(5);
        titular.setText("Gestión de espectaculos");
        jScrollPane1.setViewportView(titular);

        tablaEspectaculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Zona", "Inicio", "Duración", "Aforo", "Plazas", "Showman"
            }
        ));
        tablaEspectaculos.setColumnSelectionAllowed(true);
        tablaEspectaculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEspectaculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEspectaculos);
        tablaEspectaculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        panelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del espectaculo"));

        textID.setText("ID");

        textFieldID.setToolTipText("");

        textNombre.setText("Nombre");

        textFieldNombre.addActionListener(this::textFieldNombreActionPerformed);

        textZona.setText("Zona");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        textInicio.setText("Inicio");

        textDuracion.setText("Duración");

        textFieldDuracion.addActionListener(this::textFieldDuracionActionPerformed);

        textAforo.setText("Aforo");

        textFieldAforo.addActionListener(this::textFieldAforoActionPerformed);

        textPlazas.setText("Plazas");

        textFieldPlazas.addActionListener(this::textFieldPlazasActionPerformed);

        jLabel1.setText("Showman");

        comboShowman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNombre)
                    .addComponent(textID)
                    .addComponent(textZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldID)
                    .addComponent(textFieldNombre)
                    .addComponent(jComboBox1, 0, 115, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDuracion)
                    .addComponent(textAforo)
                    .addComponent(textInicio))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAforo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textPlazas)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldPlazas, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(comboShowman, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textID)
                            .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textInicio)
                            .addComponent(textFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPlazas)
                            .addComponent(textFieldPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(panelDetallesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textNombre)
                                        .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboShowman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(textDuracion))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textZona)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textAforo)
                        .addComponent(textFieldAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(this::botonNuevoActionPerformed);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(this::botonGuardarActionPerformed);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(this::botonEliminarActionPerformed);

        botonSalir.setForeground(new java.awt.Color(255, 51, 102));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addGap(33, 33, 33)
                        .addComponent(botonGuardar)
                        .addGap(38, 38, 38)
                        .addComponent(botonEliminar)
                        .addGap(255, 255, 255)
                        .addComponent(botonSalir))
                    .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDuracionActionPerformed

    private void textFieldPlazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPlazasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPlazasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void textFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void textFieldAforoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldAforoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAforoActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        limpiarFormulario();
        textFieldID.setEditable(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try {
        String idStr = textFieldID.getText().trim();
        String nombre = textFieldNombre.getText().trim();
        String zona = (String) jComboBox1.getSelectedItem();
        String showman = (String) comboShowman.getSelectedItem();

        if (nombre.isEmpty() || zona == null || showman == null) {
            JOptionPane.showMessageDialog(this, "Por favor rellena todos los campos obligatorios");
            return;
        }

        String fechaStr = textFieldInicio.getText().trim();
        if (fechaStr.length() == 10) {
            fechaStr = fechaStr + " 12:00:00";
        }

        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        java.util.Date fechaUtil = sdf.parse(fechaStr);
        java.sql.Timestamp timestamp = new java.sql.Timestamp(fechaUtil.getTime());

        int duracion = Integer.parseInt(textFieldDuracion.getText().trim());
        int aforo = Integer.parseInt(textFieldAforo.getText().trim());

        if (idStr.isEmpty()) {
            Espectaculo e = new Espectaculo(0, nombre, aforo, timestamp, duracion, showman, zona);
            fa.añadirEspectaculo(e);
        } else {
            int id = Integer.parseInt(idStr);
            Espectaculo e = new Espectaculo(id, nombre, aforo, timestamp, duracion, showman, zona);
            fa.modificarEspectaculo(e);
        }

        cargarEspectaculos();
        limpiarFormulario();
        JOptionPane.showMessageDialog(this, "Espectáculo guardado correctamente");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: duración y aforo deben ser números");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        int fila = tablaEspectaculos.getSelectedRow();
        if (fila < 0) return;
    
        int id = (int) tablaEspectaculos.getValueAt(fila, 0);
        fa.eliminarEspectaculo(id);
        cargarEspectaculos();
        limpiarFormulario();
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void tablaEspectaculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEspectaculosMouseClicked
                int fila = tablaEspectaculos.getSelectedRow();
        if (fila >= 0) {
            textFieldID.setText(String.valueOf(tablaEspectaculos.getValueAt(fila, 0)));
            textFieldNombre.setText((String) tablaEspectaculos.getValueAt(fila, 1));
            jComboBox1.setSelectedItem(tablaEspectaculos.getValueAt(fila, 2));
            textFieldInicio.setText(String.valueOf(tablaEspectaculos.getValueAt(fila, 3)));
            textFieldDuracion.setText(String.valueOf(tablaEspectaculos.getValueAt(fila, 4)));
            textFieldAforo.setText(String.valueOf(tablaEspectaculos.getValueAt(fila, 5)));
            textFieldPlazas.setText(String.valueOf(tablaEspectaculos.getValueAt(fila, 6)));
            comboShowman.setSelectedItem(tablaEspectaculos.getValueAt(fila, 7));
            textFieldID.setEditable(false);
        }
    }//GEN-LAST:event_tablaEspectaculosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> comboShowman;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JTable tablaEspectaculos;
    private javax.swing.JLabel textAforo;
    private java.awt.TextArea textArea1;
    private javax.swing.JLabel textDuracion;
    private javax.swing.JTextField textFieldAforo;
    private javax.swing.JTextField textFieldDuracion;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldInicio;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldPlazas;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textInicio;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textPlazas;
    private javax.swing.JLabel textZona;
    private javax.swing.JTextArea titular;
    // End of variables declaration//GEN-END:variables
}
