/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import aplicacion.Espectaculo;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumnogreibd
 */
public class VGestionEspectaculos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VGestionEspectaculos.class.getName());

    private FachadaGui fgui; // Referencia a la fachada
    private DefaultTableModel modeloTabla;

    /**
     * Constructor modificado para integrarse en la aplicación
     */
    public VGestionEspectaculos(java.awt.Frame parent, boolean modal, FachadaGui fgui) {
        super(parent, modal);
        this.fgui = fgui;
        initComponents();
        this.setLocationRelativeTo(parent); // Centrar respecto a la ventana principal
        buscarEspectaculos();
    }
    
    /**
     * Pide la lista de espectáculos a la BD y rellena la tabla visual
     */
    private void buscarEspectaculos() {
        // 1. Pedimos los datos usando la arquitectura en capas
        List<Espectaculo> lista = fgui.getFachadaAplicacion().listarEspectaculos();

        // 2. Preparamos el modelo de la tabla
        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Evita que se edite la celda directamente haciendo doble clic
            }
        };

        // 3. Definimos las columnas
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Aforo");
        modeloTabla.addColumn("Hora Inicio");
        modeloTabla.addColumn("Duración (min)");
        modeloTabla.addColumn("Zona");
        modeloTabla.addColumn("Showman");

        // 4. Rellenamos las filas con los objetos recibidos
        for (Espectaculo e : lista) {
            Object[] fila = new Object[7];
            fila[0] = e.getIdEspectaculo();
            fila[1] = e.getNombre();
            fila[2] = e.getAforo();
            fila[3] = e.getHoraInicio(); // Asegúrate de que esto se muestra bien, si no habrá que formatear
            fila[4] = e.getDuracion();
            fila[5] = e.getZona();
            fila[6] = e.getShowman();
            modeloTabla.addRow(fila);
        }

        // 5. Aplicamos el modelo a la tabla visual
        tablaEspectaculos.setModel(modeloTabla);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        titular = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEspectaculos = new javax.swing.JTable();
        panelDetalles = new javax.swing.JPanel();
        textID = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        textNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textZona = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textInicio = new javax.swing.JLabel();
        textFieldInicio = new javax.swing.JTextField();
        textDuracion = new javax.swing.JLabel();
        textFieldDuracion = new javax.swing.JTextField();
        textAforo = new javax.swing.JLabel();
        textFieldAforo = new javax.swing.JTextField();
        textPlazas = new javax.swing.JLabel();
        textFieldPlazas = new javax.swing.JTextField();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titular.setColumns(20);
        titular.setRows(5);
        titular.setText("Gestión de espectaculos");
        jScrollPane1.setViewportView(titular);

        tablaEspectaculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Zona", "Inicio", "Duración", "Aforo", "Plazas"
            }
        ));
        tablaEspectaculos.setColumnSelectionAllowed(true);
        tablaEspectaculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEspectaculosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaEspectaculos);
        tablaEspectaculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        panelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del espectaculo"));

        textID.setText("ID");

        textFieldID.setToolTipText("");

        textNombre.setText("Nombre");

        textZona.setText("Zona");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textInicio.setText("Inicio");

        textDuracion.setText("Duración");

        textFieldDuracion.addActionListener(this::textFieldDuracionActionPerformed);

        textAforo.setText("Aforo");

        textPlazas.setText("Plazas");

        textFieldPlazas.addActionListener(this::textFieldPlazasActionPerformed);

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNombre)
                    .addComponent(textID)
                    .addComponent(textZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldID)
                    .addComponent(textFieldNombre)
                    .addComponent(jComboBox1, 0, 115, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDuracion)
                    .addComponent(textAforo)
                    .addComponent(textInicio))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(textFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(textPlazas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(textFieldAforo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textID)
                            .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textInicio)
                            .addComponent(textFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPlazas)
                            .addComponent(textFieldPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDetallesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textNombre)
                                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(textDuracion))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textZona)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textAforo)
                        .addComponent(textFieldAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(this::botonNuevoActionPerformed);

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(this::botonGuardarActionPerformed);

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(this::botonEliminarActionPerformed);

        botonSalir.setForeground(new java.awt.Color(255, 51, 102));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addGap(33, 33, 33)
                        .addComponent(botonGuardar)
                        .addGap(38, 38, 38)
                        .addComponent(botonEliminar)
                        .addGap(255, 255, 255)
                        .addComponent(botonSalir))
                    .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDuracionActionPerformed

    private void textFieldPlazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPlazasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPlazasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void tablaEspectaculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEspectaculosMouseClicked
        int filaSeleccionada = tablaEspectaculos.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
            // Cogemos los valores de la fila seleccionada y los pasamos a los JTextFields
            textFieldID.setText(modeloTabla.getValueAt(filaSeleccionada, 0).toString());
            textFieldNombre.setText(modeloTabla.getValueAt(filaSeleccionada, 1).toString());
            textFieldAforo.setText(modeloTabla.getValueAt(filaSeleccionada, 2).toString());
            
            // Si la fecha o la zona son null, evitamos el NullPointerException
            Object horaObj = modeloTabla.getValueAt(filaSeleccionada, 3);
            textFieldInicio.setText(horaObj != null ? horaObj.toString() : "");
            
            Object duracionObj = modeloTabla.getValueAt(filaSeleccionada, 4);
            textFieldDuracion.setText(duracionObj != null ? duracionObj.toString() : "");
            
            // Seleccionamos la zona en el combobox (asumiendo que tiene los nombres correctos)
            Object zonaObj = modeloTabla.getValueAt(filaSeleccionada, 5);
            if(zonaObj != null) {
                jComboBox1.setSelectedItem(zonaObj.toString());
            }
        }
    }//GEN-LAST:event_tablaEspectaculosMouseClicked

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        textFieldID.setText("");
        textFieldNombre.setText("");
        textFieldInicio.setText("");
        textFieldDuracion.setText("");
        textFieldAforo.setText("");
        textFieldPlazas.setText("");
        textFieldNombre.requestFocus();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try {
            // Validaciones básicas obligatorias
            if (textFieldNombre.getText().isEmpty() || textFieldAforo.getText().isEmpty()) {
                fgui.muestraAviso("El nombre y el aforo son campos obligatorios.");
                return;
            }

            // Extraer datos de los campos de texto
            String nombre = textFieldNombre.getText();
            int aforo = Integer.parseInt(textFieldAforo.getText());
            String zona = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : null;
            
            // Tratamiento seguro de la fecha y hora
            java.sql.Timestamp horaInicio = null;
            if(!textFieldInicio.getText().isEmpty()) {
                // El formato esperado es "YYYY-MM-DD HH:MM:SS"
                horaInicio = java.sql.Timestamp.valueOf(textFieldInicio.getText()); 
            }
            
            // Tratamiento de la duración
            Integer duracion = null;
            if(!textFieldDuracion.getText().isEmpty()) {
                duracion = Integer.valueOf(textFieldDuracion.getText());
            }

            // Evaluar si es Inserción o Actualización
            if (textFieldID.getText().isEmpty()) {
                // ES NUEVO: Creamos el objeto (con ID 0 porque la BD generará uno)
                Espectaculo nuevo = new Espectaculo(0, nombre, aforo, horaInicio, duracion, null, zona);
                fgui.getFachadaAplicacion().añadirEspectaculo(nuevo);
                fgui.muestraAviso("Espectáculo creado correctamente.");
                
            } else {
                // Lo actualizamos
                int id = Integer.parseInt(textFieldID.getText());
                Espectaculo modificado = new Espectaculo(id, nombre, aforo, horaInicio, duracion, null, zona);
                fgui.getFachadaAplicacion().modificarEspectaculo(modificado);
                fgui.muestraAviso("Espectáculo actualizado correctamente.");
            }
            
            // Refrescar la tabla y limpiar el formulario
            buscarEspectaculos(); 
            botonNuevoActionPerformed(evt); // Llamamos al botón nuevo para que vacíe los campos

        } catch (NumberFormatException ex) {
            fgui.muestraExcepcion("Error: Revisa que Aforo y Duración sean números válidos.");
        } catch (IllegalArgumentException ex) {
            fgui.muestraExcepcion("Formato de fecha incorrecto. Usa exactamente: AAAA-MM-DD HH:MM:SS");
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
       // Comprobar que hay algo seleccionado
        if (textFieldID.getText().isEmpty()) {
            fgui.muestraAviso("Por favor, selecciona un espectáculo de la tabla para eliminarlo.");
            return;
        }

        // Pedir confirmación visual
        boolean confirmado = fgui.pideConfirmacion("¿Estás seguro de que deseas eliminar este espectáculo? Esta acción no se puede deshacer.");
        
        // Ejecutar la orden si dice que "Sí"
        if (confirmado) {
            int id = Integer.parseInt(textFieldID.getText());
            fgui.getFachadaAplicacion().eliminarEspectaculo(id);
            fgui.muestraAviso("Espectáculo eliminado.");
            
            // Refrescar y limpiar
            buscarEspectaculos();
            botonNuevoActionPerformed(evt); 
        }
    }//GEN-LAST:event_botonEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JTable tablaEspectaculos;
    private javax.swing.JLabel textAforo;
    private java.awt.TextArea textArea1;
    private javax.swing.JLabel textDuracion;
    private javax.swing.JTextField textFieldAforo;
    private javax.swing.JTextField textFieldDuracion;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldInicio;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldPlazas;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textInicio;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textPlazas;
    private javax.swing.JLabel textZona;
    private javax.swing.JTextArea titular;
    // End of variables declaration//GEN-END:variables
}
