/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;


/**
 *
 * @author sebas
 */
public class VGestionUsuarios extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VLogin.class.getName());
    private aplicacion.FachadaAplicacion fa;

    /**
     * Creates new form VGestionUsuarios
     */
    public VGestionUsuarios(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nombreLabel1 = new javax.swing.JLabel();
        nombreTextField1 = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosTable1 = new javax.swing.JTable();
        idLabel1 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        claveLabel3 = new javax.swing.JLabel();
        nuevoButton1 = new javax.swing.JButton();
        guardarButton2 = new javax.swing.JButton();
        eliminarButton3 = new javax.swing.JButton();
        salirButton4 = new javax.swing.JButton();
        idTextField1 = new javax.swing.JTextField();
        emailTextField2 = new javax.swing.JTextField();
        claveTextField2 = new javax.swing.JTextField();
        nombreLabel4 = new javax.swing.JLabel();
        telefonoLabel5 = new javax.swing.JLabel();
        nombreTextField2 = new javax.swing.JTextField();
        telefonoTextField2 = new javax.swing.JTextField();
        permisosLabel6 = new javax.swing.JLabel();
        nacimientoLabel7 = new javax.swing.JLabel();
        nacimientoTextField1 = new javax.swing.JTextField();
        buscarButton1 = new javax.swing.JButton();
        ap1Label9 = new javax.swing.JLabel();
        ap1TextField1 = new javax.swing.JTextField();
        ap2Label2 = new javax.swing.JLabel();
        ap2TextField1 = new javax.swing.JTextField();
        permisosCheckBox1 = new javax.swing.JCheckBox();

        idLabel.setText("ID");

        nombreLabel1.setText("Nombre");

        emailLabel1.setText("Email");

        datosTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email", "Teléfono", "Permisos"
            }
        ));
        jScrollPane2.setViewportView(datosTable1);

        idLabel1.setText("ID");

        emailLabel2.setText("Email");

        claveLabel3.setText("Clave");

        nuevoButton1.setText("Nuevo");
        nuevoButton1.addActionListener(this::nuevoButton1ActionPerformed);

        guardarButton2.setText("Guardar");
        guardarButton2.addActionListener(this::guardarButton2ActionPerformed);

        eliminarButton3.setText("Eliminar");
        eliminarButton3.addActionListener(this::eliminarButton3ActionPerformed);

        salirButton4.setText("Salir");
        salirButton4.addActionListener(this::salirButton4ActionPerformed);

        nombreLabel4.setText("Nombre");

        telefonoLabel5.setText("Teléfono");

        nombreTextField2.setToolTipText("");

        permisosLabel6.setText("Permisos");

        nacimientoLabel7.setText("Nacimiento");

        nacimientoTextField1.setToolTipText("dd/mm/aaaa");

        buscarButton1.setText("Buscar");
        buscarButton1.addActionListener(this::buscarButton1ActionPerformed);

        ap1Label9.setText("Apellido1");

        ap2Label2.setText("Apellido2");

        permisosCheckBox1.setText("Es Admin?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(claveLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(claveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ap1Label9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ap1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ap2Label2)
                        .addGap(18, 18, 18)
                        .addComponent(ap2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel2)
                            .addComponent(idLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(telefonoLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nombreLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(permisosLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(permisosCheckBox1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(telefonoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nacimientoLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(nacimientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(salirButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel1)
                    .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel1)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel1)
                    .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel4)
                    .addComponent(nombreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permisosLabel6)
                    .addComponent(permisosCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel5)
                    .addComponent(telefonoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimientoLabel7)
                    .addComponent(nacimientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveLabel3)
                    .addComponent(claveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap1Label9)
                    .addComponent(ap1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap2Label2)
                    .addComponent(ap2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton1)
                    .addComponent(guardarButton2)
                    .addComponent(eliminarButton3)
                    .addComponent(salirButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButton1ActionPerformed
        if (idTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El ID no puede estar vacío.");
            return;
        }

        Integer ID;
        try {
            ID = Integer.valueOf(idTextField1.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
            return;
        }

        LocalDate fecha;
        try {
            fecha = LocalDate.parse(nacimientoTextField1.getText().trim(), 
                        DateTimeFormatter.ofPattern("dd/MM/yyyy"));
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa dd/mm/aaaa.");
            return;
        }
        
        String Nombre = nombreTextField2.getText();
        String ap1 = ap1Label9.getText();
        String ap2 = ap2Label2.getText();
        String clave = claveTextField2.getText();
        String email = emailTextField2.getText();
        String telefono = telefonoTextField2.getText();
        Boolean permisos = permisosCheckBox1.isSelected();
                
        aplicacion.Usuario u = new aplicacion.Usuario(ID,Nombre,ap1,ap2,clave,email,telefono,fecha,permisos);
        
        fa.crearCuenta(u);
    }//GEN-LAST:event_nuevoButton1ActionPerformed

    private void guardarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButton2ActionPerformed
        
    }//GEN-LAST:event_guardarButton2ActionPerformed

    private void eliminarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButton3ActionPerformed
        if (idTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El ID no puede estar vacío.");
            return;
        }

        Integer ID;
        try {
            ID = Integer.valueOf(idTextField1.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número.");
            return;
        }
        
        fa.eliminarUsuario(ID);
    }//GEN-LAST:event_eliminarButton3ActionPerformed

    private void salirButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButton4ActionPerformed
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_salirButton4ActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void cargarTabla() {
        java.util.List<aplicacion.Usuario> usuarios = fa.obtenerUsuarios(null,null);
         javax.swing.table.DefaultTableModel  modelo = ( javax.swing.table.DefaultTableModel ) datosTable1.getModel();
        modelo.setRowCount(0);
        for (aplicacion.Usuario u : usuarios) {
            modelo.addRow(new Object[]{
                u.getIdUsuario(), u.getNombre(), u.getEmail(),
                u.getTelefono(), u.isPermisos()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ap1Label9;
    private javax.swing.JTextField ap1TextField1;
    private javax.swing.JLabel ap2Label2;
    private javax.swing.JTextField ap2TextField1;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JLabel claveLabel3;
    private javax.swing.JTextField claveTextField2;
    private javax.swing.JTable datosTable1;
    private javax.swing.JButton eliminarButton3;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JTextField emailTextField2;
    private javax.swing.JButton guardarButton2;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nacimientoLabel7;
    private javax.swing.JTextField nacimientoTextField1;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel nombreLabel4;
    private javax.swing.JTextField nombreTextField1;
    private javax.swing.JTextField nombreTextField2;
    private javax.swing.JButton nuevoButton1;
    private javax.swing.JCheckBox permisosCheckBox1;
    private javax.swing.JLabel permisosLabel6;
    private javax.swing.JButton salirButton4;
    private javax.swing.JLabel telefonoLabel5;
    private javax.swing.JTextField telefonoTextField2;
    // End of variables declaration//GEN-END:variables
}
