/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.Entrada;
import aplicacion.FachadaAplicacion;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alumnogreibd
 */
public class VGestionEntradas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VGestionEntradas.class.getName());
    private final FachadaAplicacion fa;

    /**
     * Creates new form VGestionEntradas
     */
    public VGestionEntradas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.fa = new FachadaAplicacion();
        textDesde.setText(LocalDate.now().minusDays(30).toString());
        textHasta.setText(LocalDate.now().toString());
        buscarEntradas();
    }
    
    private void buscarEntradas() {
    LocalDate desde = LocalDate.parse(textDesde.getText());
    LocalDate hasta = LocalDate.parse(textHasta.getText());
    
    List<Entrada> entradas = fa.consultarEntradasVendidas(desde, hasta);
    
    DefaultTableModel modelo = new DefaultTableModel(
        new String[]{"ID", "Usuario", "Fecha", "Precio", "Estado"}, 0);
    
    int total = 0;
    double recaudacion = 0;
    
    for (Entrada e : entradas) {
        modelo.addRow(new Object[]{
            e.getIdEntrada(),
            e.getIdUsuario(),
            e.getFecha(),
            e.getPrecio() + "€",
            e.isActivo() ? "Activa" : "Anulada"
        });
        if (e.isActivo()) {
            total++;
            recaudacion += e.getPrecio();
        }
    }
    
    tablaPrincipal.setModel(modelo);
    textTotalEntradas.setText(String.valueOf(total));
    textRecaudacion.setText(String.format("%.2f€", recaudacion));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDesde = new javax.swing.JLabel();
        textDesde = new javax.swing.JTextField();
        labelHasta = new javax.swing.JLabel();
        textHasta = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPrincipal = new javax.swing.JTable();
        labelTotalEntradas = new javax.swing.JLabel();
        textTotalEntradas = new javax.swing.JTextField();
        labelRecaudacion = new javax.swing.JLabel();
        textRecaudacion = new javax.swing.JTextField();
        botonSalir = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelDesde.setText("Desde");

        textDesde.addActionListener(this::textDesdeActionPerformed);

        labelHasta.setText("Hasta");

        textHasta.addActionListener(this::textHastaActionPerformed);

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(this::botonBuscarActionPerformed);

        tablaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Fecha", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tablaPrincipal);

        labelTotalEntradas.setText("Total entradas");

        textTotalEntradas.addActionListener(this::textTotalEntradasActionPerformed);

        labelRecaudacion.setText("Recaudación");

        textRecaudacion.addActionListener(this::textRecaudacionActionPerformed);

        botonSalir.setForeground(new java.awt.Color(255, 0, 51));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Gestión de entradas");
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(457, 457, 457)
                        .addComponent(botonSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDesde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(labelHasta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(botonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelTotalEntradas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textTotalEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(labelRecaudacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDesde)
                    .addComponent(textDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHasta)
                    .addComponent(textHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalEntradas)
                    .addComponent(textTotalEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRecaudacion)
                    .addComponent(textRecaudacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonSalir)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDesdeActionPerformed
        buscarEntradas();
    }//GEN-LAST:event_textDesdeActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        buscarEntradas();
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void textTotalEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTotalEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTotalEntradasActionPerformed

    private void textRecaudacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRecaudacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textRecaudacionActionPerformed

    private void textHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHastaActionPerformed
        buscarEntradas();
    }//GEN-LAST:event_textHastaActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VGestionEntradas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelDesde;
    private javax.swing.JLabel labelHasta;
    private javax.swing.JLabel labelRecaudacion;
    private javax.swing.JLabel labelTotalEntradas;
    private javax.swing.JTable tablaPrincipal;
    private javax.swing.JTextField textDesde;
    private javax.swing.JTextField textHasta;
    private javax.swing.JTextField textRecaudacion;
    private javax.swing.JTextField textTotalEntradas;
    // End of variables declaration//GEN-END:variables

}
