/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import aplicacion.Animal;
import aplicacion.Trabajador;
import java.util.List;

/**
 *
 * @author manue
 */
public class VGestionAnimales extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VGestionAnimales.class.getName());

    private aplicacion.FachadaAplicacion fa;
    
    private List<Animal> animalesActuales = new java.util.ArrayList<>();
    
    /**
     * Creates new form VGestionAnimal
     */
    public VGestionAnimales() {
        initComponents();
        cargarZonas(); //Para la comboBox
       // buscarAnimales(); //Para la tabla 
        //TODO: Esperar a que implementen los de dev2 para los cuidadores
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        animalPanel1 = new javax.swing.JPanel();
        nombreComunLabel2 = new javax.swing.JLabel();
        nombreCientificoTextField1 = new javax.swing.JTextField();
        idTextField1 = new javax.swing.JTextField();
        nombreCientificoLabel1 = new javax.swing.JLabel();
        idLabel2 = new javax.swing.JLabel();
        idTextField2 = new javax.swing.JTextField();
        buscarButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        idLabel1 = new javax.swing.JLabel();
        nombreCientificoTextField2 = new javax.swing.JTextField();
        nombreComunLabel1 = new javax.swing.JLabel();
        nombreComunTextField2 = new javax.swing.JTextField();
        nombreCientificoLabel3 = new javax.swing.JLabel();
        nombreComunTextField1 = new javax.swing.JTextField();
        zonaLabel1 = new javax.swing.JLabel();
        estadoConservaLabel1 = new javax.swing.JLabel();
        ZonaComboBox1 = new javax.swing.JComboBox<>();
        estadoConservaComboBox2 = new javax.swing.JComboBox<>();
        alimentacionLabel1 = new javax.swing.JLabel();
        descripcionLabel1 = new javax.swing.JLabel();
        alimentacionTextField1 = new javax.swing.JTextField();
        descripcionTextField1 = new javax.swing.JTextField();
        nuevoAnimalButton2 = new javax.swing.JButton();
        guardarAnimalButton2 = new javax.swing.JButton();
        eliminarAnimalButton4 = new javax.swing.JButton();
        salirAnimalButton1 = new javax.swing.JButton();
        historialPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigoTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        diagnosticoTextField1 = new javax.swing.JTextField();
        veterinarioComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fechaTextField1 = new javax.swing.JTextField();
        nuevoHistorialButton1 = new javax.swing.JButton();
        guardarHistorialButton1 = new javax.swing.JButton();
        borrarHistorialButton1 = new javax.swing.JButton();
        salirHistorialButton1 = new javax.swing.JButton();
        cuidadoresPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cuidadoresNoDisponiblesList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        cuidadoresDisponiblesList2 = new javax.swing.JList<>();
        insertarNoDisponiblesButton1 = new javax.swing.JButton();
        insertarDisponiblesButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        actualizarButton1 = new javax.swing.JButton();
        salirCuidadoresButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombreComunLabel2.setText("Nombre común");

        nombreCientificoLabel1.setText("Nombre científico");

        idLabel2.setText("ID");

        buscarButton1.setLabel("Buscar");
        buscarButton1.addActionListener(this::buscarButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre común", "Nombre científico", "Zona", "Estado de Conserva"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Datos del animal seleccionado:");

        idLabel1.setText("ID");

        nombreComunLabel1.setText("Nombre común");

        nombreCientificoLabel3.setText("Nombre científico");

        zonaLabel1.setText("Zona");

        estadoConservaLabel1.setText("Estado de conserva");

        ZonaComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        estadoConservaComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        alimentacionLabel1.setText("Alimentación");

        descripcionLabel1.setText("Descripción");

        nuevoAnimalButton2.setText("Nuevo");
        nuevoAnimalButton2.addActionListener(this::nuevoAnimalButton2ActionPerformed);

        guardarAnimalButton2.setText("Guardar");
        guardarAnimalButton2.addActionListener(this::guardarAnimalButton2ActionPerformed);

        eliminarAnimalButton4.setText("Eliminar");
        eliminarAnimalButton4.addActionListener(this::eliminarAnimalButton4ActionPerformed);

        salirAnimalButton1.setText("Salir");
        salirAnimalButton1.addActionListener(this::salirAnimalButton1ActionPerformed);

        javax.swing.GroupLayout animalPanel1Layout = new javax.swing.GroupLayout(animalPanel1);
        animalPanel1.setLayout(animalPanel1Layout);
        animalPanel1Layout.setHorizontalGroup(
            animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animalPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreComunLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreComunTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nombreCientificoLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCientificoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(idLabel1)
                .addGap(18, 18, 18)
                .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(buscarButton1)
                .addContainerGap())
            .addGroup(animalPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(animalPanel1Layout.createSequentialGroup()
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(animalPanel1Layout.createSequentialGroup()
                                .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(animalPanel1Layout.createSequentialGroup()
                                        .addComponent(idLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(idTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(animalPanel1Layout.createSequentialGroup()
                                        .addComponent(nombreCientificoLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreCientificoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(19, 19, 19))
                            .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addGroup(animalPanel1Layout.createSequentialGroup()
                                    .addComponent(nombreComunLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombreComunTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(animalPanel1Layout.createSequentialGroup()
                                    .addComponent(zonaLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ZonaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(1, 1, 1)))
                            .addGroup(animalPanel1Layout.createSequentialGroup()
                                .addComponent(estadoConservaLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoConservaComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(187, 187, 187)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(animalPanel1Layout.createSequentialGroup()
                                .addComponent(descripcionLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descripcionTextField1))
                            .addGroup(animalPanel1Layout.createSequentialGroup()
                                .addComponent(alimentacionLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alimentacionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(animalPanel1Layout.createSequentialGroup()
                        .addComponent(nuevoAnimalButton2)
                        .addGap(18, 18, 18)
                        .addComponent(guardarAnimalButton2)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarAnimalButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirAnimalButton1)
                        .addGap(40, 40, 40))))
            .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(animalPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        animalPanel1Layout.setVerticalGroup(
            animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(animalPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreComunLabel1)
                    .addComponent(nombreComunTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCientificoLabel1)
                    .addComponent(nombreCientificoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idLabel1)
                    .addComponent(idTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animalPanel1Layout.createSequentialGroup()
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alimentacionLabel1)
                            .addComponent(alimentacionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(descripcionLabel1)
                            .addComponent(descripcionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animalPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idLabel2)
                            .addComponent(idTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreComunLabel2)
                            .addComponent(nombreComunTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreCientificoLabel3)
                            .addComponent(nombreCientificoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zonaLabel1)
                            .addComponent(ZonaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoConservaLabel1)
                            .addComponent(estadoConservaComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoAnimalButton2)
                    .addComponent(guardarAnimalButton2)
                    .addComponent(eliminarAnimalButton4)
                    .addComponent(salirAnimalButton1))
                .addGap(11, 11, 11))
            .addGroup(animalPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, animalPanel1Layout.createSequentialGroup()
                    .addContainerGap(77, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(240, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Animales", animalPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Fecha", "Diagnóstico", "Veterinario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable2);

        jLabel4.setText("Nuevo / Editar Registro");

        jLabel5.setText("Código");

        jLabel6.setText("Diagnóstico");

        jLabel7.setText("Veterinario");

        veterinarioComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Fecha");

        nuevoHistorialButton1.setText("Nuevo registro");
        nuevoHistorialButton1.addActionListener(this::nuevoHistorialButton1ActionPerformed);

        guardarHistorialButton1.setText("Guardar registro");
        guardarHistorialButton1.addActionListener(this::guardarHistorialButton1ActionPerformed);

        borrarHistorialButton1.setText("Borrar");
        borrarHistorialButton1.addActionListener(this::borrarHistorialButton1ActionPerformed);

        salirHistorialButton1.setText("Salir");

        javax.swing.GroupLayout historialPanel2Layout = new javax.swing.GroupLayout(historialPanel2);
        historialPanel2.setLayout(historialPanel2Layout);
        historialPanel2Layout.setHorizontalGroup(
            historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(historialPanel2Layout.createSequentialGroup()
                        .addGroup(historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addGroup(historialPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaTextField1))
                            .addGroup(historialPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diagnosticoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(historialPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(veterinarioComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 314, Short.MAX_VALUE))
                    .addGroup(historialPanel2Layout.createSequentialGroup()
                        .addComponent(nuevoHistorialButton1)
                        .addGap(18, 18, 18)
                        .addComponent(guardarHistorialButton1)
                        .addGap(18, 18, 18)
                        .addComponent(borrarHistorialButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirHistorialButton1)))
                .addContainerGap())
        );
        historialPanel2Layout.setVerticalGroup(
            historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historialPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codigoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fechaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diagnosticoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(veterinarioComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(historialPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoHistorialButton1)
                    .addComponent(guardarHistorialButton1)
                    .addComponent(borrarHistorialButton1)
                    .addComponent(salirHistorialButton1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Historial Médico", historialPanel2);

        cuidadoresNoDisponiblesList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(cuidadoresNoDisponiblesList1);

        cuidadoresDisponiblesList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(cuidadoresDisponiblesList2);

        insertarNoDisponiblesButton1.setText("---->");
        insertarNoDisponiblesButton1.addActionListener(this::insertarNoDisponiblesButton1ActionPerformed);

        insertarDisponiblesButton2.setText("<----");
        insertarDisponiblesButton2.addActionListener(this::insertarDisponiblesButton2ActionPerformed);

        jLabel1.setText("Cuidadores disponibles");

        jLabel2.setText("Cuidadores no disponibles");

        actualizarButton1.setText("Actualizar");
        actualizarButton1.addActionListener(this::actualizarButton1ActionPerformed);

        salirCuidadoresButton3.setText("Salir");
        salirCuidadoresButton3.addActionListener(this::salirCuidadoresButton3ActionPerformed);

        javax.swing.GroupLayout cuidadoresPanel3Layout = new javax.swing.GroupLayout(cuidadoresPanel3);
        cuidadoresPanel3.setLayout(cuidadoresPanel3Layout);
        cuidadoresPanel3Layout.setHorizontalGroup(
            cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuidadoresPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuidadoresPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cuidadoresPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(insertarNoDisponiblesButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuidadoresPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(insertarDisponiblesButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))))
                    .addGroup(cuidadoresPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cuidadoresPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(actualizarButton1)
                .addGap(36, 36, 36)
                .addComponent(salirCuidadoresButton3)
                .addGap(28, 28, 28))
        );
        cuidadoresPanel3Layout.setVerticalGroup(
            cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuidadoresPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cuidadoresPanel3Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(insertarNoDisponiblesButton1)
                        .addGap(18, 18, 18)
                        .addComponent(insertarDisponiblesButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(cuidadoresPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarButton1)
                    .addComponent(salirCuidadoresButton3))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Cuidadores", cuidadoresPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 824, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirAnimalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirAnimalButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirAnimalButton1ActionPerformed

    private void eliminarAnimalButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAnimalButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarAnimalButton4ActionPerformed

    private void guardarAnimalButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAnimalButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarAnimalButton2ActionPerformed

    private void nuevoAnimalButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAnimalButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoAnimalButton2ActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void insertarNoDisponiblesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarNoDisponiblesButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertarNoDisponiblesButton1ActionPerformed

    private void insertarDisponiblesButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarDisponiblesButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertarDisponiblesButton2ActionPerformed

    private void actualizarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actualizarButton1ActionPerformed

    private void salirCuidadoresButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirCuidadoresButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salirCuidadoresButton3ActionPerformed

    private void nuevoHistorialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoHistorialButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoHistorialButton1ActionPerformed

    private void guardarHistorialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarHistorialButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarHistorialButton1ActionPerformed

    private void borrarHistorialButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarHistorialButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarHistorialButton1ActionPerformed

    private void cargarZonas() {
        ZonaComboBox1.removeAllItems();
        for (String zona : fa.obtenerNombresZonas()) {
            ZonaComboBox1.addItem(zona);
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ZonaComboBox1;
    private javax.swing.JButton actualizarButton1;
    private javax.swing.JLabel alimentacionLabel1;
    private javax.swing.JTextField alimentacionTextField1;
    private javax.swing.JPanel animalPanel1;
    private javax.swing.JButton borrarHistorialButton1;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JTextField codigoTextField1;
    private javax.swing.JList<String> cuidadoresDisponiblesList2;
    private javax.swing.JList<String> cuidadoresNoDisponiblesList1;
    private javax.swing.JPanel cuidadoresPanel3;
    private javax.swing.JLabel descripcionLabel1;
    private javax.swing.JTextField descripcionTextField1;
    private javax.swing.JTextField diagnosticoTextField1;
    private javax.swing.JButton eliminarAnimalButton4;
    private javax.swing.JComboBox<String> estadoConservaComboBox2;
    private javax.swing.JLabel estadoConservaLabel1;
    private javax.swing.JTextField fechaTextField1;
    private javax.swing.JButton guardarAnimalButton2;
    private javax.swing.JButton guardarHistorialButton1;
    private javax.swing.JPanel historialPanel2;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JTextField idTextField1;
    private javax.swing.JTextField idTextField2;
    private javax.swing.JButton insertarDisponiblesButton2;
    private javax.swing.JButton insertarNoDisponiblesButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel nombreCientificoLabel1;
    private javax.swing.JLabel nombreCientificoLabel3;
    private javax.swing.JTextField nombreCientificoTextField1;
    private javax.swing.JTextField nombreCientificoTextField2;
    private javax.swing.JLabel nombreComunLabel1;
    private javax.swing.JLabel nombreComunLabel2;
    private javax.swing.JTextField nombreComunTextField1;
    private javax.swing.JTextField nombreComunTextField2;
    private javax.swing.JButton nuevoAnimalButton2;
    private javax.swing.JButton nuevoHistorialButton1;
    private javax.swing.JButton salirAnimalButton1;
    private javax.swing.JButton salirCuidadoresButton3;
    private javax.swing.JButton salirHistorialButton1;
    private javax.swing.JComboBox<String> veterinarioComboBox1;
    private javax.swing.JLabel zonaLabel1;
    // End of variables declaration//GEN-END:variables
}
