/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

/**
 *
 * @author alumnogreibd
 */
public class VGestionEspectaculos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VGestionEspectaculos.class.getName());

private FachadaGui fgui; // Referencia a la fachada

    /**
     * Constructor modificado para integrarse en la aplicación
     */
    public VGestionEspectaculos(java.awt.Frame parent, boolean modal, FachadaGui fgui) {
        super(parent, modal);
        this.fgui = fgui;
        initComponents();
        this.setLocationRelativeTo(parent); // Centrar respecto a la ventana principal
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        titular = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaEspectaculos = new javax.swing.JTable();
        panelDetalles = new javax.swing.JPanel();
        textID = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        textNombre = new javax.swing.JLabel();
        textFieldNombre = new javax.swing.JTextField();
        textZona = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textInicio = new javax.swing.JLabel();
        textFieldInicio = new javax.swing.JTextField();
        textDuracion = new javax.swing.JLabel();
        textFieldDuracion = new javax.swing.JTextField();
        textAforo = new javax.swing.JLabel();
        textFieldAforo = new javax.swing.JTextField();
        textPlazas = new javax.swing.JLabel();
        textFieldPlazas = new javax.swing.JTextField();
        botonNuevo = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titular.setColumns(20);
        titular.setRows(5);
        titular.setText("Gestión de espectaculos");
        jScrollPane1.setViewportView(titular);

        tablaEspectaculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Zona", "Inicio", "Duración", "Aforo", "Plazas"
            }
        ));
        tablaEspectaculos.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tablaEspectaculos);
        tablaEspectaculos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        panelDetalles.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles del espectaculo"));

        textID.setText("ID");

        textFieldID.setToolTipText("");

        textNombre.setText("Nombre");

        textZona.setText("Zona");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        textInicio.setText("Inicio");

        textDuracion.setText("Duración");

        textFieldDuracion.addActionListener(this::textFieldDuracionActionPerformed);

        textAforo.setText("Aforo");

        textPlazas.setText("Plazas");

        textFieldPlazas.addActionListener(this::textFieldPlazasActionPerformed);

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNombre)
                    .addComponent(textID)
                    .addComponent(textZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldID)
                    .addComponent(textFieldNombre)
                    .addComponent(jComboBox1, 0, 115, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDuracion)
                    .addComponent(textAforo)
                    .addComponent(textInicio))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addComponent(textFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(textPlazas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldDuracion, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                        .addComponent(textFieldAforo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDetallesLayout.createSequentialGroup()
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textID)
                            .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textInicio)
                            .addComponent(textFieldInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textPlazas)
                            .addComponent(textFieldPlazas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDetallesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textNombre)
                                    .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(textDuracion))
                .addGap(18, 18, 18)
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textZona)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textAforo)
                        .addComponent(textFieldAforo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonNuevo.setText("Nuevo");

        botonGuardar.setText("Guardar");

        botonEliminar.setText("Eliminar");

        botonSalir.setForeground(new java.awt.Color(255, 51, 102));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addGap(33, 33, 33)
                        .addComponent(botonGuardar)
                        .addGap(38, 38, 38)
                        .addComponent(botonEliminar)
                        .addGap(255, 255, 255)
                        .addComponent(botonSalir))
                    .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(panelDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo)
                    .addComponent(botonGuardar)
                    .addComponent(botonEliminar)
                    .addComponent(botonSalir))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDuracionActionPerformed

    private void textFieldPlazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPlazasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPlazasActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDetalles;
    private javax.swing.JTable tablaEspectaculos;
    private javax.swing.JLabel textAforo;
    private java.awt.TextArea textArea1;
    private javax.swing.JLabel textDuracion;
    private javax.swing.JTextField textFieldAforo;
    private javax.swing.JTextField textFieldDuracion;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldInicio;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldPlazas;
    private javax.swing.JLabel textID;
    private javax.swing.JLabel textInicio;
    private javax.swing.JLabel textNombre;
    private javax.swing.JLabel textPlazas;
    private javax.swing.JLabel textZona;
    private javax.swing.JTextArea titular;
    // End of variables declaration//GEN-END:variables
}
