/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;
import aplicacion.*;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class VGestionTrabajadores extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VGestionTrabajadores.class.getName());

    private FachadaGui fgui;

    /**
     * Constructor adaptado
     */
    public VGestionTrabajadores(java.awt.Frame parent, boolean modal, FachadaGui fgui) {
        super(parent, modal); // Ahora sí funcionará porque es un JDialog
        this.fgui = fgui;
        initComponents();
        this.setLocationRelativeTo(parent);
        inicializarCombos();
        cargarTrabajadores();
    }

    private void inicializarCombos() {
        String[] tipos = {"","Cuidador", "Veterinario", "Showman", "Guía", "Seguridad"};
        tipoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(tipos));
        tipoComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(tipos));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dniLabel1 = new javax.swing.JLabel();
        dniTextField1 = new javax.swing.JTextField();
        nombreLabel1 = new javax.swing.JLabel();
        nombreTextField1 = new javax.swing.JTextField();
        tipoLabel2 = new javax.swing.JLabel();
        tipoComboBox1 = new javax.swing.JComboBox<>();
        buscarButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dniTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tipoComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        direccionTextField1 = new javax.swing.JTextField();
        nacimientoTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sexoTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefonoTextField1 = new javax.swing.JTextField();
        sueldoTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        equipamientoTextField1 = new javax.swing.JTextField();
        especialidadTextField1 = new javax.swing.JTextField();
        nuevoButton1 = new javax.swing.JButton();
        guardarButton1 = new javax.swing.JButton();
        eliminarButton1 = new javax.swing.JButton();
        salirButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ap1TextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ap2TextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        dniLabel1.setText("DNI");

        dniTextField1.setColumns(5);

        nombreLabel1.setText("Nombre");

        nombreTextField1.setColumns(5);

        tipoLabel2.setText("Tipo");

        tipoComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buscarButton1.setText("Buscar");
        buscarButton1.addActionListener(this::buscarButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Email", "Tipo", "Sueldo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("DNI");

        dniTextField2.setColumns(5);

        jLabel2.setText("Nombre");

        nombreTextField2.setColumns(5);

        jLabel3.setText("Tipo");

        tipoComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Dirección");

        jLabel5.setText("F. Nacimiento");

        direccionTextField1.setColumns(10);

        nacimientoTextField1.setColumns(8);

        jLabel6.setText("Email");

        emailTextField1.setColumns(8);

        jLabel7.setText("Sexo");

        sexoTextField1.setColumns(1);

        jLabel8.setText("Sueldo");

        jLabel9.setText("Teléfono");

        telefonoTextField1.setColumns(8);

        sueldoTextField1.setColumns(4);

        jLabel10.setText("Equipamiento");

        jLabel11.setText("Especialidad");

        equipamientoTextField1.setColumns(5);

        especialidadTextField1.setColumns(5);

        nuevoButton1.setText("Nuevo");
        nuevoButton1.addActionListener(this::nuevoButton1ActionPerformed);

        guardarButton1.setText("Guardar");
        guardarButton1.addActionListener(this::guardarButton1ActionPerformed);

        eliminarButton1.setText("Eliminar");
        eliminarButton1.addActionListener(this::eliminarButton1ActionPerformed);

        salirButton1.setText("Salir");
        salirButton1.addActionListener(this::salirButton1ActionPerformed);

        jLabel12.setText("Apellido1");

        ap1TextField1.setColumns(5);

        jLabel13.setText("Apellido2");

        ap2TextField1.setColumns(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(dniLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dniTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(nombreLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(tipoLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(buscarButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dniTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equipamientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nacimientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(guardarButton1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sexoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sueldoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(eliminarButton1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(direccionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ap1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(ap2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(especialidadTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(telefonoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(salirButton1))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(nuevoButton1)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniLabel1)
                    .addComponent(dniTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel1)
                    .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoLabel2)
                    .addComponent(tipoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dniTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nombreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tipoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(equipamientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ap1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(ap2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(direccionTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(telefonoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nacimientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(sexoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(sueldoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(especialidadTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton1)
                    .addComponent(guardarButton1)
                    .addComponent(eliminarButton1)
                    .addComponent(salirButton1))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        cargarTrabajadores();
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void cargarTrabajadores(){
        String dni = dniTextField1.getText().trim();
        String nombre = nombreTextField1.getText().trim();
        String tipoSeleccionado = (String) tipoComboBox1.getSelectedItem();
        if (tipoSeleccionado == null) tipoSeleccionado = "";

        java.util.List<aplicacion.Trabajador> trabajadores = fgui.getFachadaAplicacion().buscarTrabajadoresFiltro(dni, nombre);

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
                new String[]{"DNI", "Nombre", "Email", "Tipo", "Sueldo"}, 0);

        for (aplicacion.Trabajador t : trabajadores) {
            String tipoReal = t.getTipoTrabajo();

            if (tipoSeleccionado.isEmpty() || tipoSeleccionado.equalsIgnoreCase(tipoReal)) {
                modelo.addRow(new Object[]{
                        t.getDni(),
                        t.getNombre(),
                        t.getEmail(),
                        tipoReal,
                        t.getSueldo()
                });
            }
        }
        jTable1.setModel(modelo);
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila >= 0) {
            String dni = (String) jTable1.getValueAt(fila, 0);
            dniTextField2.setText(dni);
            nombreTextField2.setText((String) jTable1.getValueAt(fila, 1));
            emailTextField1.setText((String) jTable1.getValueAt(fila, 2));
            tipoComboBox2.setSelectedItem(jTable1.getValueAt(fila, 3).toString());
            sueldoTextField1.setText(String.valueOf(jTable1.getValueAt(fila, 4)));
            Trabajador t = fgui.getFachadaAplicacion().buscarTrabajadorPorDni(dni);
            direccionTextField1.setText(t.getDireccion());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            nacimientoTextField1.setText(t.getFechaNacimiento().format(dtf));
            sexoTextField1.setText(String.valueOf(t.getSexo()));
            telefonoTextField1.setText(t.getTelefonoContacto());
            ap2TextField1.setText(t.getAp1());
            ap1TextField1.setText(t.getAp2());
                      
            if (t instanceof Guia) {   
                especialidadTextField1.setText(((Guia) t).getEspecialidad());               
            } else if (t instanceof Seguridad) {
                equipamientoTextField1.setText(((Seguridad) t).getEquipamiento());
            }else{
                especialidadTextField1.setText("");             
                equipamientoTextField1.setText("");
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void nuevoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButton1ActionPerformed
        String dni = dniTextField2.getText().trim();
        String nombre = nombreTextField2.getText().trim();
        String ap1 = ap1TextField1.getText().trim();
        String ap2 = ap2TextField1.getText().trim();
        String direccion = direccionTextField1.getText().trim();
        String telefono = telefonoTextField1.getText().trim();
        String email = emailTextField1.getText().trim();
        char sexo = sexoTextField1.getText().trim().charAt(0);
        LocalDate fecha;
        try {
            fecha = LocalDate.parse(nacimientoTextField1.getText().trim(), 
                        DateTimeFormatter.ofPattern("dd-MM-yyyy"));
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa dd/mm/aaaa.");
            return;
        }
        double sueldo = Double.parseDouble(sueldoTextField1.getText().trim());
        String equipamiento = equipamientoTextField1.getText().trim();
        String especialidad = especialidadTextField1.getText().trim();
        
        String tipo = (String) tipoComboBox2.getSelectedItem().toString();
        
        Trabajador t;
        switch (tipo) {
            case "Veterinario":
                t = new Veterinario(dni, nombre, ap1, ap2, direccion, telefono, email, sexo, fecha, sueldo);
                break;
            case "Cuidador":
                t = new Cuidador(dni, nombre, ap1, ap2, direccion, telefono, email, sexo, fecha, sueldo);
                break;
            case "Showman":
                t = new Showman(dni, nombre, ap1, ap2, direccion, telefono, email, sexo, fecha, sueldo);
                break;
            case "Guía":
                t = new Guia(dni, nombre, ap1, ap2, direccion, telefono, email, sexo, fecha, sueldo,equipamiento);
                break;
            case "Seguridad":
                t = new Seguridad(dni, nombre, ap1, ap2, direccion, telefono, email, sexo, fecha, sueldo,especialidad);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Selecciona un tipo de trabajador.");
                return;
        }
        
        fgui.getFachadaAplicacion().darAltaTrabajador(t);
        cargarTrabajadores();
    }//GEN-LAST:event_nuevoButton1ActionPerformed

    private void guardarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButton1ActionPerformed
        
    }//GEN-LAST:event_guardarButton1ActionPerformed

    private void eliminarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButton1ActionPerformed
        int fila = jTable1.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Selecciona un trabajador de la tabla para eliminar.");
            return;
        }

        String dni = (String) jTable1.getValueAt(fila, 0);
        fgui.getFachadaAplicacion().darBajaTrabajador(dni);
        cargarTrabajadores();
    }//GEN-LAST:event_eliminarButton1ActionPerformed

    private void salirButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_salirButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ap1TextField1;
    private javax.swing.JTextField ap2TextField1;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JTextField direccionTextField1;
    private javax.swing.JLabel dniLabel1;
    private javax.swing.JTextField dniTextField1;
    private javax.swing.JTextField dniTextField2;
    private javax.swing.JButton eliminarButton1;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JTextField equipamientoTextField1;
    private javax.swing.JTextField especialidadTextField1;
    private javax.swing.JButton guardarButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nacimientoTextField1;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JTextField nombreTextField1;
    private javax.swing.JTextField nombreTextField2;
    private javax.swing.JButton nuevoButton1;
    private javax.swing.JButton salirButton1;
    private javax.swing.JTextField sexoTextField1;
    private javax.swing.JTextField sueldoTextField1;
    private javax.swing.JTextField telefonoTextField1;
    private javax.swing.JComboBox<String> tipoComboBox1;
    private javax.swing.JComboBox<String> tipoComboBox2;
    private javax.swing.JLabel tipoLabel2;
    // End of variables declaration//GEN-END:variables
}
