/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;
import aplicacion.Usuario;
import aplicacion.FachadaAplicacion;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;


/**
 *
 * @author alumnogreibd
 */
public class VGestionUsuarios extends javax.swing.JPanel {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VLogin.class.getName());
    private aplicacion.FachadaAplicacion fa;
    private java.util.List<aplicacion.Usuario> usuariosActuales = new java.util.ArrayList<>();
    private int idSeleccionado = -1;

    /**
     * Creates new form VGestionUsuarios
     */
    public VGestionUsuarios(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;      
        initComponents();   
        cargarTabla();     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nombreLabel1 = new javax.swing.JLabel();
        nombreTextField1 = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        emailTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        datosTable1 = new javax.swing.JTable();
        emailLabel2 = new javax.swing.JLabel();
        claveLabel3 = new javax.swing.JLabel();
        nuevoButton1 = new javax.swing.JButton();
        guardarButton2 = new javax.swing.JButton();
        eliminarButton3 = new javax.swing.JButton();
        salirButton4 = new javax.swing.JButton();
        emailTextField2 = new javax.swing.JTextField();
        claveTextField2 = new javax.swing.JTextField();
        nombreLabel4 = new javax.swing.JLabel();
        telefonoLabel5 = new javax.swing.JLabel();
        nombreTextField2 = new javax.swing.JTextField();
        telefonoTextField2 = new javax.swing.JTextField();
        permisosLabel6 = new javax.swing.JLabel();
        nacimientoLabel7 = new javax.swing.JLabel();
        nacimientoTextField1 = new javax.swing.JTextField();
        buscarButton1 = new javax.swing.JButton();
        ap1Label9 = new javax.swing.JLabel();
        ap1TextField1 = new javax.swing.JTextField();
        ap2Label2 = new javax.swing.JLabel();
        ap2TextField1 = new javax.swing.JTextField();
        permisosCheckBox1 = new javax.swing.JCheckBox();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        idLabel.setText("ID");

        idTextField.addActionListener(this::idTextFieldActionPerformed);

        nombreLabel1.setText("Nombre");

        nombreTextField1.addActionListener(this::nombreTextField1ActionPerformed);

        emailLabel1.setText("Email");

        emailTextField1.addActionListener(this::emailTextField1ActionPerformed);

        datosTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Email", "Teléfono", "Permisos"
            }
        ));
        datosTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datosTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(datosTable1);

        emailLabel2.setText("Email");

        claveLabel3.setText("Clave");

        nuevoButton1.setText("Nuevo");
        nuevoButton1.addActionListener(this::nuevoButton1ActionPerformed);

        guardarButton2.setText("Guardar");
        guardarButton2.addActionListener(this::guardarButton2ActionPerformed);

        eliminarButton3.setText("Eliminar");
        eliminarButton3.addActionListener(this::eliminarButton3ActionPerformed);

        salirButton4.setForeground(new java.awt.Color(255, 0, 51));
        salirButton4.setText("Salir");
        salirButton4.addActionListener(this::salirButton4ActionPerformed);

        emailTextField2.addActionListener(this::emailTextField2ActionPerformed);

        claveTextField2.addActionListener(this::claveTextField2ActionPerformed);

        nombreLabel4.setText("Nombre");

        telefonoLabel5.setText("Teléfono");

        nombreTextField2.setToolTipText("");
        nombreTextField2.addActionListener(this::nombreTextField2ActionPerformed);

        telefonoTextField2.addActionListener(this::telefonoTextField2ActionPerformed);

        permisosLabel6.setText("Permisos");

        nacimientoLabel7.setText("Nacimiento");

        nacimientoTextField1.setToolTipText("dd/mm/aaaa");
        nacimientoTextField1.addActionListener(this::nacimientoTextField1ActionPerformed);

        buscarButton1.setText("Buscar");
        buscarButton1.addActionListener(this::buscarButton1ActionPerformed);

        ap1Label9.setText("Apellido1");

        ap1TextField1.addActionListener(this::ap1TextField1ActionPerformed);

        ap2Label2.setText("Apellido2");

        ap2TextField1.addActionListener(this::ap2TextField1ActionPerformed);

        permisosCheckBox1.setText("Es Admin?");
        permisosCheckBox1.addActionListener(this::permisosCheckBox1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombreLabel4)
                                    .addComponent(claveLabel3)
                                    .addComponent(emailLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(telefonoLabel5)
                                                .addGap(18, 18, 18))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(claveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9)
                                                .addComponent(nacimientoLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(telefonoTextField2)
                                            .addComponent(ap1TextField1)
                                            .addComponent(nacimientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nombreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ap1Label9)
                                        .addGap(112, 112, 112)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(permisosLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(permisosCheckBox1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ap2Label2)
                                        .addGap(13, 13, 13)
                                        .addComponent(ap2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(idLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idTextField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscarButton1)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nuevoButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirButton4)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreLabel1)
                    .addComponent(nombreTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel1)
                    .addComponent(emailTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap1TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap1Label9)
                    .addComponent(ap2TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ap2Label2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel2)
                    .addComponent(emailTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoLabel5)
                    .addComponent(telefonoTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(permisosLabel6)
                    .addComponent(permisosCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(claveLabel3)
                    .addComponent(claveTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimientoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimientoLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton1)
                    .addComponent(guardarButton2)
                    .addComponent(eliminarButton3)
                    .addComponent(salirButton4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoButton1ActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_nuevoButton1ActionPerformed
        // Validamos que al menos haya escrito el nombre
        if (nombreTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El Nombre es obligatorio para crear un usuario.");
            return;
        }

        // Calculamos el siguiente ID disponible automáticamente
        int idCalculado = 1;
        for (aplicacion.Usuario u : usuariosActuales) {
            if (u.getIdUsuario() >= idCalculado) {
                idCalculado = u.getIdUsuario() + 1;
            }
        }

        // Recogemos los datos de los campos de texto
        LocalDate fecha = null;
        if (!nacimientoTextField1.getText().trim().isEmpty()) {
            try {
                fecha = LocalDate.parse(nacimientoTextField1.getText().trim(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            } catch (DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa dd/MM/yyyy.");
                return;
            }
        }
        
        String nombre = nombreTextField2.getText().trim();
        String ap1 = ap1TextField1.getText().trim();
        String ap2 = ap2TextField1.getText().trim();
        String email = emailTextField2.getText().trim();
        String telefono = telefonoTextField2.getText().trim();
        String clave = claveTextField2.getText().trim();
        boolean permisos = permisosCheckBox1.isSelected();

        try {
            // Creamos el usuario con el ID autocalculado y lo guardamos
            aplicacion.Usuario u = new aplicacion.Usuario(idCalculado, nombre, ap1, ap2, clave, email, telefono, fecha, permisos);
            fa.crearCuenta(u);
            
            JOptionPane.showMessageDialog(this, "Cuenta creada correctamente con el ID: " + idCalculado);
            
            // Recargamos la tabla y vaciamos los campos visuales
            cargarTabla();
            nombreTextField2.setText("");
            ap1TextField1.setText("");
            ap2TextField1.setText("");
            emailTextField2.setText("");
            telefonoTextField2.setText("");
            claveTextField2.setText("");
            nacimientoTextField1.setText("");
            permisosCheckBox1.setSelected(false);
            
            idSeleccionado = -1; // Reseteamos la memoria
            datosTable1.clearSelection();
            
        } catch (Exception e) {
            fa.muestraExcepcion("Error al crear la cuenta: " + e.getMessage());
        }
    }//GEN-LAST:event_nuevoButton1ActionPerformed

    private void guardarButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButton2ActionPerformed
        // Verificamos en memoria si hay alguien seleccionado
        if (idSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario de la tabla para modificar sus datos.");
            return;
        }

        try {
            // Recogemos los datos (modificados o no)
            String nombre = nombreTextField2.getText().trim();
            String ap1 = ap1TextField1.getText().trim();
            String ap2 = ap2TextField1.getText().trim();
            String email = emailTextField2.getText().trim();
            String telefono = telefonoTextField2.getText().trim();
            String clave = claveTextField2.getText().trim();

            LocalDate fecha = null;
            if (!nacimientoTextField1.getText().trim().isEmpty()) {
                fecha = LocalDate.parse(nacimientoTextField1.getText().trim(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            }
            boolean permisos = permisosCheckBox1.isSelected();

            // Actualizamos en la base de datos usando el ID que guardamos en memoria
            aplicacion.Usuario u = new aplicacion.Usuario(idSeleccionado, nombre, ap1, ap2, clave, email, telefono, fecha, permisos);
            fa.editarDatos(u);

            JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.");
            cargarTabla();

        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Usa dd/MM/yyyy.");
        } catch (Exception ex) {
            fa.muestraExcepcion("Error al modificar el usuario: " + ex.getMessage());
        }
    }//GEN-LAST:event_guardarButton2ActionPerformed

    private void eliminarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButton3ActionPerformed
        if (idSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona un usuario de la tabla primero para eliminarlo.");
            return;
        }
        
        int confirmacion = JOptionPane.showConfirmDialog(this, 
                "¿Estás seguro de que deseas eliminar al usuario con ID " + idSeleccionado + "?", 
                "Confirmar borrado", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.WARNING_MESSAGE);
                
        if (confirmacion == JOptionPane.YES_OPTION) {
            try {
                fa.eliminarUsuario(idSeleccionado);
                JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente.");
                
                cargarTabla();
                
                // Limpiamos los cuadros de texto
                nombreTextField2.setText("");
                ap1TextField1.setText("");
                ap2TextField1.setText("");
                emailTextField2.setText("");
                telefonoTextField2.setText("");
                claveTextField2.setText("");
                nacimientoTextField1.setText("");
                permisosCheckBox1.setSelected(false);
                
                idSeleccionado = -1; // Vaciamos la memoria
                
            } catch (Exception ex) {
                fa.muestraExcepcion("Error al eliminar: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_eliminarButton3ActionPerformed

    private void salirButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButton4ActionPerformed
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_salirButton4ActionPerformed

    private void buscarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButton1ActionPerformed
        String id = idTextField.getText().trim();
        String nombre = nombreTextField1.getText().trim();
    
        usuariosActuales = fa.obtenerUsuarios(id, nombre);
    
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) datosTable1.getModel();
        modelo.setRowCount(0);
    
        for (Usuario u : usuariosActuales) {
            modelo.addRow(new Object[]{
                u.getIdUsuario(),
                u.getNombre() + " " + u.getAp1() + " " + u.getAp2(),
                u.getEmail(),
                u.getTelefono(),
                u.isPermisos() ? "Admin" : "Usuario"
            });
        }
    }//GEN-LAST:event_buscarButton1ActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void nombreTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextField1ActionPerformed

    private void emailTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField1ActionPerformed

    private void nombreTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextField2ActionPerformed

    private void permisosCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permisosCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permisosCheckBox1ActionPerformed

    private void nacimientoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacimientoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacimientoTextField1ActionPerformed

    private void telefonoTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTextField2ActionPerformed

    private void emailTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextField2ActionPerformed

    private void claveTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveTextField2ActionPerformed

    private void ap1TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap1TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap1TextField1ActionPerformed

    private void ap2TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ap2TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ap2TextField1ActionPerformed

    private void datosTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datosTable1MouseClicked
        int filaSeleccionada = datosTable1.getSelectedRow();
        
        if (filaSeleccionada >= 0 && usuariosActuales != null && filaSeleccionada < usuariosActuales.size()) {
            Usuario u = usuariosActuales.get(filaSeleccionada);
            
            // Guardamos el ID en memoria
            idSeleccionado = u.getIdUsuario(); 
            
            nombreTextField2.setText(u.getNombre());
            ap1TextField1.setText(u.getAp1());
            ap2TextField1.setText(u.getAp2());
            emailTextField2.setText(u.getEmail());
            telefonoTextField2.setText(u.getTelefono());
            claveTextField2.setText(u.getClave());
            permisosCheckBox1.setSelected(u.isPermisos());
            
            if (u.getFechaNacimiento() != null) {
                nacimientoTextField1.setText(u.getFechaNacimiento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
            } else {
                nacimientoTextField1.setText("");
            }
        }
    }//GEN-LAST:event_datosTable1MouseClicked

    private void cargarTabla() {
        usuariosActuales = fa.obtenerUsuarios(null, null);
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) datosTable1.getModel();
        modelo.setRowCount(0);
        for (aplicacion.Usuario u : usuariosActuales) {
            modelo.addRow(new Object[]{
                u.getIdUsuario(), 
                u.getNombre(), 
                u.getEmail(),
                u.getTelefono(), 
                u.isPermisos() ? "Admin" : "Usuario"
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ap1Label9;
    private javax.swing.JTextField ap1TextField1;
    private javax.swing.JLabel ap2Label2;
    private javax.swing.JTextField ap2TextField1;
    private javax.swing.JButton buscarButton1;
    private javax.swing.JLabel claveLabel3;
    private javax.swing.JTextField claveTextField2;
    private javax.swing.JTable datosTable1;
    private javax.swing.JButton eliminarButton3;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JTextField emailTextField1;
    private javax.swing.JTextField emailTextField2;
    private javax.swing.JButton guardarButton2;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nacimientoLabel7;
    private javax.swing.JTextField nacimientoTextField1;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JLabel nombreLabel4;
    private javax.swing.JTextField nombreTextField1;
    private javax.swing.JTextField nombreTextField2;
    private javax.swing.JButton nuevoButton1;
    private javax.swing.JCheckBox permisosCheckBox1;
    private javax.swing.JLabel permisosLabel6;
    private javax.swing.JButton salirButton4;
    private javax.swing.JLabel telefonoLabel5;
    private javax.swing.JTextField telefonoTextField2;
    // End of variables declaration//GEN-END:variables
}
