/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author alumnogreibd
 */
public class VPrincipalUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VPrincipalUsuario.class.getName());

    private aplicacion.FachadaAplicacion fa;

    private aplicacion.Usuario usuarioActual;

    public VPrincipalUsuario(aplicacion.FachadaAplicacion fa, aplicacion.Usuario usuarioActual) {
        this.fa = fa;
        this.usuarioActual = usuarioActual;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoParque2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonMapa = new javax.swing.JButton();
        botonAnimales = new javax.swing.JButton();
        textoComprar2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonComprar = new javax.swing.JButton();
        botonReservar = new javax.swing.JButton();
        textoCuenta2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botonEditar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        textoParque = new javax.swing.JMenu();
        textoComprar = new javax.swing.JMenu();
        textoCuenta = new javax.swing.JMenu();
        textoSistema = new javax.swing.JMenu();
        itemCerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoParque2.setText("Parque");

        botonMapa.setText("Mapa del parque");
        botonMapa.addActionListener(this::botonMapaActionPerformed);

        botonAnimales.setText("Animales");
        botonAnimales.addActionListener(this::botonAnimalesActionPerformed);

        textoComprar2.setText("Comprar");

        botonComprar.setText("Comprar Entrada");
        botonComprar.addActionListener(this::botonComprarActionPerformed);

        botonReservar.setText("Reservar Espectáculo");
        botonReservar.addActionListener(this::botonReservarActionPerformed);

        textoCuenta2.setText("Mi Cuenta");

        botonEditar.setText("Editar mis datos");
        botonEditar.addActionListener(this::botonEditarActionPerformed);

        menuBar.setToolTipText("");

        textoParque.setText("Parque");
        menuBar.add(textoParque);

        textoComprar.setText("Comprar");
        menuBar.add(textoComprar);

        textoCuenta.setText("Mi Cuenta");
        menuBar.add(textoCuenta);

        textoSistema.setText("Sistema");

        itemCerrarSesion.setText("Cerrar sesión");
        itemCerrarSesion.addActionListener(this::itemCerrarSesionActionPerformed);
        textoSistema.add(itemCerrarSesion);

        menuBar.add(textoSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonMapa)
                        .addGap(48, 48, 48)
                        .addComponent(botonAnimales)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(botonReservar)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoParque2)
                            .addComponent(textoComprar2)
                            .addComponent(textoCuenta2)
                            .addComponent(botonEditar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(textoParque2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMapa)
                    .addComponent(botonAnimales))
                .addGap(18, 18, 18)
                .addComponent(textoComprar2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonComprar)
                    .addComponent(botonReservar))
                .addGap(18, 18, 18)
                .addComponent(textoCuenta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEditar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMapaActionPerformed
        new VAnimales(fa).setVisible(true);
    }//GEN-LAST:event_botonMapaActionPerformed

    private void botonAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnimalesActionPerformed
        new VMapa(fa).setVisible(true);
    }//GEN-LAST:event_botonAnimalesActionPerformed

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        // T7 - dev2 lo implementa
    }//GEN-LAST:event_botonComprarActionPerformed

    private void botonReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReservarActionPerformed
        // T8 - dev2 lo implementa
    }//GEN-LAST:event_botonReservarActionPerformed

    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        new VEditarDatos(fa, usuarioActual).setVisible(true);
    }//GEN-LAST:event_botonEditarActionPerformed

    private void itemCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarSesionActionPerformed
        dispose();
        new VLogin(fa).setVisible(true);
    }//GEN-LAST:event_itemCerrarSesionActionPerformed

    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new VPrincipalUsuario().setVisible(true));
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnimales;
    private javax.swing.JButton botonComprar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonMapa;
    private javax.swing.JButton botonReservar;
    private javax.swing.JMenuItem itemCerrarSesion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu textoComprar;
    private javax.swing.JLabel textoComprar2;
    private javax.swing.JMenu textoCuenta;
    private javax.swing.JLabel textoCuenta2;
    private javax.swing.JMenu textoParque;
    private javax.swing.JLabel textoParque2;
    private javax.swing.JMenu textoSistema;
    // End of variables declaration//GEN-END:variables
}
