/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import aplicacion.FachadaAplicacion;
import javax.swing.JFrame;

/**
 *
 * @author alumnogreibd
 */
public class VPrincipalAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VPrincipalAdmin.class.getName());

    private FachadaGui fgui;
    private FachadaAplicacion fa;
    
    /**
     * Creates new form VPrincipalAdmin
     */
    public VPrincipalAdmin(FachadaGui fgui) {
        this.fgui = fgui;
        initComponents();
        this.setLocationRelativeTo(null); // Para que aparezca centrada en la pantalla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCatalogo = new javax.swing.JPanel();
        botonAnimales = new javax.swing.JButton();
        panelPersonal = new javax.swing.JPanel();
        botonTrabajadores = new javax.swing.JButton();
        botonUsuarios = new javax.swing.JButton();
        panelInstalaciones = new javax.swing.JPanel();
        botonZonas = new javax.swing.JButton();
        panelOperaciones = new javax.swing.JPanel();
        botonEntradas = new javax.swing.JButton();
        botonEspectaculo = new javax.swing.JButton();
        panelInformes = new javax.swing.JPanel();
        botonEntradasVendidas = new javax.swing.JButton();
        botonHistorial = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuCatalogo = new javax.swing.JMenu();
        menuPersonal = new javax.swing.JMenu();
        menuInstalaciones = new javax.swing.JMenu();
        menuOperaciones = new javax.swing.JMenu();
        menuInformes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCatalogo.setBorder(javax.swing.BorderFactory.createTitledBorder("Catálogo"));

        botonAnimales.setText("Animales");
        botonAnimales.addActionListener(this::botonAnimalesActionPerformed);

        javax.swing.GroupLayout panelCatalogoLayout = new javax.swing.GroupLayout(panelCatalogo);
        panelCatalogo.setLayout(panelCatalogoLayout);
        panelCatalogoLayout.setHorizontalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAnimales)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCatalogoLayout.setVerticalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCatalogoLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(botonAnimales)
                .addContainerGap())
        );

        panelPersonal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Personal")));

        botonTrabajadores.setText("Trabajadores");
        botonTrabajadores.addActionListener(this::botonTrabajadoresActionPerformed);

        botonUsuarios.setText("Usuarios");
        botonUsuarios.addActionListener(this::botonUsuariosActionPerformed);

        javax.swing.GroupLayout panelPersonalLayout = new javax.swing.GroupLayout(panelPersonal);
        panelPersonal.setLayout(panelPersonalLayout);
        panelPersonalLayout.setHorizontalGroup(
            panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonTrabajadores)
                .addGap(18, 18, 18)
                .addComponent(botonUsuarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPersonalLayout.setVerticalGroup(
            panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTrabajadores)
                    .addComponent(botonUsuarios))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInstalaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Instalaciones"));

        botonZonas.setText("Zonas");

        javax.swing.GroupLayout panelInstalacionesLayout = new javax.swing.GroupLayout(panelInstalaciones);
        panelInstalaciones.setLayout(panelInstalacionesLayout);
        panelInstalacionesLayout.setHorizontalGroup(
            panelInstalacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstalacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonZonas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInstalacionesLayout.setVerticalGroup(
            panelInstalacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstalacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonZonas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOperaciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        botonEntradas.setText("Entradas");
        botonEntradas.addActionListener(this::botonEntradasActionPerformed);

        botonEspectaculo.setText("Espectaculos");
        botonEspectaculo.addActionListener(this::botonEspectaculoActionPerformed);

        javax.swing.GroupLayout panelOperacionesLayout = new javax.swing.GroupLayout(panelOperaciones);
        panelOperaciones.setLayout(panelOperacionesLayout);
        panelOperacionesLayout.setHorizontalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEntradas)
                .addGap(30, 30, 30)
                .addComponent(botonEspectaculo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOperacionesLayout.setVerticalGroup(
            panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOperacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOperacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEntradas)
                    .addComponent(botonEspectaculo))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelInformes.setBorder(javax.swing.BorderFactory.createTitledBorder("Informes"));

        botonEntradasVendidas.setText("Entradas vendidas");
        botonEntradasVendidas.addActionListener(this::botonEntradasVendidasActionPerformed);

        botonHistorial.setText("Historial médico");
        botonHistorial.addActionListener(this::botonHistorialActionPerformed);

        javax.swing.GroupLayout panelInformesLayout = new javax.swing.GroupLayout(panelInformes);
        panelInformes.setLayout(panelInformesLayout);
        panelInformesLayout.setHorizontalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEntradasVendidas)
                .addGap(18, 18, 18)
                .addComponent(botonHistorial)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        panelInformesLayout.setVerticalGroup(
            panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEntradasVendidas)
                    .addComponent(botonHistorial))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        botonSalir.setForeground(new java.awt.Color(255, 0, 51));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(this::botonSalirActionPerformed);

        menuCatalogo.setText("Catálogo");
        menuBar.add(menuCatalogo);

        menuPersonal.setText("Personal");
        menuBar.add(menuPersonal);

        menuInstalaciones.setText("Instalaciones");
        menuBar.add(menuInstalaciones);

        menuOperaciones.setText("Operaciones");
        menuBar.add(menuOperaciones);

        menuInformes.setText("Informes");
        menuBar.add(menuInformes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPersonal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInstalaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOperaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonSalir)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInstalaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelOperaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSalir)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnimalesActionPerformed
        VGestionAnimales v = new VGestionAnimales(this, true, fgui);
        v.setVisible(true);
    }//GEN-LAST:event_botonAnimalesActionPerformed

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        VGestionUsuarios vg = new VGestionUsuarios(fa);
        JFrame frame = new JFrame("Gestión de Usuarios");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(vg);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0); // Cierra completamente la aplicación
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrabajadoresActionPerformed
        fgui.abrirGestionTrabajadores();
    }//GEN-LAST:event_botonTrabajadoresActionPerformed

    private void botonEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEspectaculoActionPerformed
        fgui.abrirGestionEspectaculos();
    }//GEN-LAST:event_botonEspectaculoActionPerformed

    private void botonEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntradasActionPerformed
        VGestionEntradas v = new VGestionEntradas();
        v.setVisible(true);
    }//GEN-LAST:event_botonEntradasActionPerformed

    private void botonEntradasVendidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntradasVendidasActionPerformed
        VGestionEntradas v = new VGestionEntradas();
        v.setVisible(true);
    }//GEN-LAST:event_botonEntradasVendidasActionPerformed

    private void botonHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHistorialActionPerformed
        VGestionAnimales v = new VGestionAnimales(this, true, fgui);
        v.setVisible(true);
    }//GEN-LAST:event_botonHistorialActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAnimales;
    private javax.swing.JButton botonEntradas;
    private javax.swing.JButton botonEntradasVendidas;
    private javax.swing.JButton botonEspectaculo;
    private javax.swing.JButton botonHistorial;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonTrabajadores;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JButton botonZonas;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCatalogo;
    private javax.swing.JMenu menuInformes;
    private javax.swing.JMenu menuInstalaciones;
    private javax.swing.JMenu menuOperaciones;
    private javax.swing.JMenu menuPersonal;
    private javax.swing.JPanel panelCatalogo;
    private javax.swing.JPanel panelInformes;
    private javax.swing.JPanel panelInstalaciones;
    private javax.swing.JPanel panelOperaciones;
    private javax.swing.JPanel panelPersonal;
    // End of variables declaration//GEN-END:variables
}
